### PR TITLE
Uncaught Error: Cannot find module 'jquery-ui/autocomplete' #114

### PR DESCRIPTION
**Pull request by dleen**
Fix issue #114 by adding a dependency on jquery-ui. This requires to pin
an older version of jquery-ui (1.10.5) since this matches the currently
committed version.

For some versions Atom seems to override the existing node_modules so
that's why the checked in version does not seem to be working in some
cases.

### CODE REVIEW

**Comment by dleen** [comment]
The diff is crappy due to removing the committed node_modules. The only change is to package.json adding:

     "jquery-ui": "1.10.5",

**Comment by skandasoft** [comment]
thanks for pitching. I think you nailed it..(But I am thinking about the 2nd part of your comment - because it happened in some cases where atom would override the module ...so I had to force it pick mine by keeping the node module as part of this..any ideas if this would happen..)

Fix issue #114 by adding a dependency on jquery-ui. **This requires to pin
an older version of jquery-ui (1.10.5)** since this matches the currently
committed version.

For some versions Atom seems to override the existing node_modules so
that's why the checked in version does not seem to be working in some
cases.

**Comment by dleen** [comment]
The "pinning" is a feature of npm and package.json. Instead of specifying "jquery-ui: ^1.10.5" (or something like ~1.10.5, notice the caret ^ and tilde ~) we specify "jquery-ui: 1.10.5". The ^ and ~ lets npm automatically use newer versions. So if we had ~1.10.5 npm would upgrade new installs to 1.12.0 which seems to have big changes compared to 1.10.5.

By specifying an exact version 1.10.5 atom won't try upgrade users to the latest version of jquery-ui.

**Comment by celiopalombo** [comment]
Ola  estoucom mesmo problema porem nao consigui ate agora , baixei pacotes open browser  e tambem ionic preview que aparece uma  mensag "first start serve  galera sou novo na areá preciso una força

**Comment by rjstone** [comment]
Here's how this can be fixed manually until the update is available:

screenshot

**Comment by respok** [comment]
adding this did not work for me.  I'm  not sure where to find the the jquery-ui file that seems to be missing from the package install.

**Pull request merged**
