### PR TITLE
word finder with 2 small tweaks

### PR DESCRIPTION
**Pull request by jamesalbert**
just a prototype, I imagine it'll get better along the way.

PS: cmd-f to open finder, ctrl-f was taken ;)

PSS: I guess the zoom in/out commands were added too. Didn't know that would happen ¯\\_(ツ)_/¯

### CODE REVIEW

**Comment by skandasoft** [comment]
Thanks for the PR. Was on vacation. 
Finder is just what I thought it would be..Couple of things I observed..

1. can the commands be at the atom work space level and can be checked if it is within browser or or not before executing ..because browser-plus-view: findon doesn't come up until the cursor is on the browser. 
2. also few enhancements on the finder
a. no of words found/
b. place holder on the input box--> "search"
c. able to go down or up on the words..(down and up arrow on the input box)

3. Also was thinking about the zoom in / zoom out to be part of plugin system as sample plugin ..for people of implement thier own key bindings ... I could not test zoom in/zoom out. when I tried command it doesn't seems to make any difference

**Comment by jamesalbert** [comment]
Hey no worries, yeah there are a bunch of caveats when it came to writing this find-on thing. The first is that you have to click inside the browser for find-on or zoom in/out to work. The second (which I probably should have asked about before I started) is I couldn't find a way to parse/manipulate the dom without injecting javascript which I don't like doing at all. I looked at webview to see if I could find a way to catch the html and do the searching and highlighting that way, but the only html I could get was Atom's which doesn't have anything within the browser itself. Injecting javascript was the only solution I found which worked. If you know of a way of doing this better, let me know!

2. Those should be straightforward to add

3. Hmm, that's weird. Are you sure you clicked inside the browser before zooming? Let me see if I can add it to a selector that will zoom it whether or not you click inside the browser first.

4. No problem

**Comment by skandasoft** [comment]
commands..what would happen if you registered to atom workspace..
1. that is right...you have to either switch on node integeration on..which is a safey issue
2. good
3. ya I think I did..and it kept adding 10 % I went up to 150% when I opened a new browser it went 140 to 150 ..infact should go to 110...and I dont' how mouse zoom in would work.
4. forget about the new patch..once you have the updates and I will merge it to mine..
5. Also we need to update the latest commands/updates to the updates.md

**Comment by skandasoft** [comment]
also let me know your thought on the plugin system. for the keyboard event rather than being submitted as a PR..we could keep the main package stable and small..add feature/keyboard events as if needed as plugins.

**Comment by jamesalbert** [comment]
Sweet, I'll check it out. Ah I see, those should be quick fixes.

I think the plugin system sounds cool, keep it as modular as possible. Some people might want a simplistic browser, some might want the entire package.

**Comment by skandasoft** [comment]
do you think can you try implementing the zoom in/zoom out as a plugin sytem..let people install this as plug in

**Comment by jamesalbert** [comment]
Yeah for sure, that should make things a little simpler on my end anyways

**Comment by skandasoft** [comment]
How are things coming up?

**Comment by jamesalbert** [comment]
In school again, things are really busy now. Let's hold off on this until I get more free time =)

**Pull request merged**
